version: '3.8'

services:
  mongo:
    image: mongo:4
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - mongo_network
    volumes:
      - ./mongo_data:/data/db

  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
        - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_USERNAME}
        
    depends_on:
      - mongo
    restart: always
    networks:
      - mongo_network

networks:
  mongo_network:
